export interface ArticleResource {
  id: string;
  slug: string;
  article_id: string;
  title: string;
  summary: string;
  content: string;
  category: string;
  country: string;
  status: string | "deleted";
  created_at: string;
  views_count: number;
  image_url: string;
  image: string;
  location?: string;
  description?: string;
  date?: string;
  views?: string;
  published_sites: string | string[];
  sites: string[];
  topics: string[];
  galleryImages: string[];
  keywords: string;
  source: string;
  original_url: string;
  is_deleted: boolean;
  is_redis: boolean;
  image_position?: number;
  image_position_x?: number;
  content_blocks: any[];
  template: string;
  author: string;

  // Restaurant Meta
  clickbait_hook?: string;
  city?: string;
  cuisine_type?: string;
  rating?: number;
  is_filipino_owned?: boolean;
  price_range?: string;
  avg_meal_cost?: string;
  budget_category?: string;
  specialty_dish?: string;
  contact_info?: string;
  why_filipinos_love_it?: string;
  menu_highlights?: string;
  google_maps_url?: string;
  address?: string;
  website?: string;
  social_media?: string;
  opening_hours?: string;
  brand_story?: string;
  tags?: string[];
  features?: string[];
}