export interface ArticleResource {
  id: string;
  slug: string;
  article_id: string;
  title: string;
  summary: string;
  content: string;
  category: string;
  country: string;
  status: string | "deleted";
  created_at: string;
  views_count: number;
  image_url: string;
  image: string;
  location?: string;
  description?: string;
  date?: string;
  views?: string;
  published_sites: string | string[];
  sites: string[];
  topics: string[];
  galleryImages: string[];
  keywords: string;
  source: string;
  original_url: string;
  is_deleted: boolean;
  is_redis: boolean;
  image_position?: number;
  image_position_x?: number;
  read_time?: string;
}